# Site settings
title: Code fairy blog
email:
description: Yet another coder's blog
baseurl: ""
url: "https://narkq.github.io"
#twitter_username: narkq
github_username: narkq
googleplus_username: AlexSladkov

# Build settings
markdown: redcarpet
highlighter: pygments
timezone: Europe/Moscow
