# Site settings
title: narkq's blog
email:
description: Yet another coder's blog
baseurl: ""
url: "https://narkq.github.io"
github_username: narkq

# Build settings
markdown: GFM
highlighter: pygments
timezone: Europe/Moscow
